name: Node.js Package

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
      - run: yarn install

      - name: Patch
        run: |
          npm version patch > version.txt

      - name: Read version.txt
        id: commit
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt

      - name: Deploy and Push
        run: |
          git config --global user.name "JIWONPARK1"
          git config --global user.email "parkj5028@gmail.com"
          git add package.json
          git commit -m "${{ (steps.commit.outputs.content) }}"
          echo ${{ (steps.commit.outputs.content) }}
          yarn deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Publish
      # - run: yarn publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.JIWON_GIT_TOKEN }}
